import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Header } from "./widgets/header/Header";
import { Providers } from "./core/providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const theme = "light"; // Установите тему на сервере

  //suppressHydrationWarning={true} что делает
  //
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <footer>footer</footer>
        </Providers>
      </body>
    </html>
  );
}
